name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Go 1.15
      uses: actions/setup-go@v1
      with: 
        go-version: 1.15

    - name: Build app 
      run: go mod download
      run: go build -o tiny-api-server .

    - name: Copy repository contents via scp
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.VPS_HOST }}
          USERNAME: ${{ secrets.VPS_USERNAME }}
          PORT: ${{ secrets.VPS_SSH_PORT }}
          KEY: ${{ secrets.SSHKEY }}
        with:
          source: './tiny-api-server'
          target: '/home'
          
      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          HOST: ${{ secrets.VPS_HOST }}
          USERNAME: ${{ secrets.VPS_USERNAME }}
          PORT: ${{ secrets.VPS_SSH_PORT }}
          KEY: ${{ secrets.SSHKEY }}
          script: systemctl restart goweb
